#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityLab
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SecurityLab2")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertRegistrations_user(Registrations_user instance);
    partial void UpdateRegistrations_user(Registrations_user instance);
    partial void DeleteRegistrations_user(Registrations_user instance);
    partial void InsertUser_Sec(User_Sec instance);
    partial void UpdateUser_Sec(User_Sec instance);
    partial void DeleteUser_Sec(User_Sec instance);
    partial void InsertSkladBas(SkladBas instance);
    partial void UpdateSkladBas(SkladBas instance);
    partial void DeleteSkladBas(SkladBas instance);
    partial void InsertCountry(Country instance);
    partial void UpdateCountry(Country instance);
    partial void DeleteCountry(Country instance);
    partial void InsertItems(Items instance);
    partial void UpdateItems(Items instance);
    partial void DeleteItems(Items instance);
    partial void InsertManufacture(Manufacture instance);
    partial void UpdateManufacture(Manufacture instance);
    partial void DeleteManufacture(Manufacture instance);
    partial void InsertModel(Model instance);
    partial void UpdateModel(Model instance);
    partial void DeleteModel(Model instance);
    partial void InsertSTB(STB instance);
    partial void UpdateSTB(STB instance);
    partial void DeleteSTB(STB instance);
    partial void InsertLessons(Lessons instance);
    partial void UpdateLessons(Lessons instance);
    partial void DeleteLessons(Lessons instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SecurityLab.Properties.Settings.Default.SecurityLab2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Registrations_user> Registrations_user
		{
			get
			{
				return this.GetTable<Registrations_user>();
			}
		}
		
		public System.Data.Linq.Table<User_Sec> User_Sec
		{
			get
			{
				return this.GetTable<User_Sec>();
			}
		}
		
		public System.Data.Linq.Table<ADMLessons> ADMLessons
		{
			get
			{
				return this.GetTable<ADMLessons>();
			}
		}
		
		public System.Data.Linq.Table<SkladView> SkladView
		{
			get
			{
				return this.GetTable<SkladView>();
			}
		}
		
		public System.Data.Linq.Table<SkladBas> SkladBas
		{
			get
			{
				return this.GetTable<SkladBas>();
			}
		}
		
		public System.Data.Linq.Table<Country> Country
		{
			get
			{
				return this.GetTable<Country>();
			}
		}
		
		public System.Data.Linq.Table<Items> Items
		{
			get
			{
				return this.GetTable<Items>();
			}
		}
		
		public System.Data.Linq.Table<Manufacture> Manufacture
		{
			get
			{
				return this.GetTable<Manufacture>();
			}
		}
		
		public System.Data.Linq.Table<Model> Model
		{
			get
			{
				return this.GetTable<Model>();
			}
		}
		
		public System.Data.Linq.Table<STB> STB
		{
			get
			{
				return this.GetTable<STB>();
			}
		}
		
		public System.Data.Linq.Table<Lessons> Lessons
		{
			get
			{
				return this.GetTable<Lessons>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registrations_user")]
	public partial class Registrations_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_regis;
		
		private string _Name_user;
		
		private string _Job;
		
		private int _id_fk_user;
		
		private EntityRef<User_Sec> _User_Sec;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_regisChanging(int value);
    partial void OnId_regisChanged();
    partial void OnName_userChanging(string value);
    partial void OnName_userChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void Onid_fk_userChanging(int value);
    partial void Onid_fk_userChanged();
    #endregion
		
		public Registrations_user()
		{
			this._User_Sec = default(EntityRef<User_Sec>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_regis", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_regis
		{
			get
			{
				return this._Id_regis;
			}
			set
			{
				if ((this._Id_regis != value))
				{
					this.OnId_regisChanging(value);
					this.SendPropertyChanging();
					this._Id_regis = value;
					this.SendPropertyChanged("Id_regis");
					this.OnId_regisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_user", DbType="NVarChar(50)")]
		public string Name_user
		{
			get
			{
				return this._Name_user;
			}
			set
			{
				if ((this._Name_user != value))
				{
					this.OnName_userChanging(value);
					this.SendPropertyChanging();
					this._Name_user = value;
					this.SendPropertyChanged("Name_user");
					this.OnName_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="NVarChar(50)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fk_user", DbType="Int NOT NULL")]
		public int id_fk_user
		{
			get
			{
				return this._id_fk_user;
			}
			set
			{
				if ((this._id_fk_user != value))
				{
					if (this._User_Sec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fk_userChanging(value);
					this.SendPropertyChanging();
					this._id_fk_user = value;
					this.SendPropertyChanged("id_fk_user");
					this.Onid_fk_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Sec_Registrations_user", Storage="_User_Sec", ThisKey="id_fk_user", OtherKey="Id_user", IsForeignKey=true)]
		public User_Sec User_Sec
		{
			get
			{
				return this._User_Sec.Entity;
			}
			set
			{
				User_Sec previousValue = this._User_Sec.Entity;
				if (((previousValue != value) 
							|| (this._User_Sec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User_Sec.Entity = null;
						previousValue.Registrations_user.Remove(this);
					}
					this._User_Sec.Entity = value;
					if ((value != null))
					{
						value.Registrations_user.Add(this);
						this._id_fk_user = value.Id_user;
					}
					else
					{
						this._id_fk_user = default(int);
					}
					this.SendPropertyChanged("User_Sec");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Sec")]
	public partial class User_Sec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_user;
		
		private string _Number_phone;
		
		private string _Pass;
		
		private System.Nullable<bool> _isenable;
		
		private EntitySet<Registrations_user> _Registrations_user;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_userChanging(int value);
    partial void OnId_userChanged();
    partial void OnNumber_phoneChanging(string value);
    partial void OnNumber_phoneChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnisenableChanging(System.Nullable<bool> value);
    partial void OnisenableChanged();
    #endregion
		
		public User_Sec()
		{
			this._Registrations_user = new EntitySet<Registrations_user>(new Action<Registrations_user>(this.attach_Registrations_user), new Action<Registrations_user>(this.detach_Registrations_user));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_user
		{
			get
			{
				return this._Id_user;
			}
			set
			{
				if ((this._Id_user != value))
				{
					this.OnId_userChanging(value);
					this.SendPropertyChanging();
					this._Id_user = value;
					this.SendPropertyChanged("Id_user");
					this.OnId_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_phone", DbType="NVarChar(20)")]
		public string Number_phone
		{
			get
			{
				return this._Number_phone;
			}
			set
			{
				if ((this._Number_phone != value))
				{
					this.OnNumber_phoneChanging(value);
					this.SendPropertyChanging();
					this._Number_phone = value;
					this.SendPropertyChanged("Number_phone");
					this.OnNumber_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(20)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isenable", DbType="Bit")]
		public System.Nullable<bool> isenable
		{
			get
			{
				return this._isenable;
			}
			set
			{
				if ((this._isenable != value))
				{
					this.OnisenableChanging(value);
					this.SendPropertyChanging();
					this._isenable = value;
					this.SendPropertyChanged("isenable");
					this.OnisenableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Sec_Registrations_user", Storage="_Registrations_user", ThisKey="Id_user", OtherKey="id_fk_user")]
		public EntitySet<Registrations_user> Registrations_user
		{
			get
			{
				return this._Registrations_user;
			}
			set
			{
				this._Registrations_user.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Registrations_user(Registrations_user entity)
		{
			this.SendPropertyChanging();
			entity.User_Sec = this;
		}
		
		private void detach_Registrations_user(Registrations_user entity)
		{
			this.SendPropertyChanging();
			entity.User_Sec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMLessons")]
	public partial class ADMLessons
	{
		
		private int _Номер_за_дания;
		
		private string _Исполнитель_первого_этапа;
		
		private string _Исполнитель_второго_этапа;
		
		private string _Исполнитель_третьего_этапа;
		
		private string _Задание;
		
		private string _Первый_этап;
		
		private string _Второй_этап;
		
		private string _Третий_этап;
		
		public ADMLessons()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер за дания]", Storage="_Номер_за_дания", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Номер_за_дания
		{
			get
			{
				return this._Номер_за_дания;
			}
			set
			{
				if ((this._Номер_за_дания != value))
				{
					this._Номер_за_дания = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Исполнитель первого этапа]", Storage="_Исполнитель_первого_этапа", DbType="NVarChar(50)")]
		public string Исполнитель_первого_этапа
		{
			get
			{
				return this._Исполнитель_первого_этапа;
			}
			set
			{
				if ((this._Исполнитель_первого_этапа != value))
				{
					this._Исполнитель_первого_этапа = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Исполнитель второго этапа]", Storage="_Исполнитель_второго_этапа", DbType="NVarChar(50)")]
		public string Исполнитель_второго_этапа
		{
			get
			{
				return this._Исполнитель_второго_этапа;
			}
			set
			{
				if ((this._Исполнитель_второго_этапа != value))
				{
					this._Исполнитель_второго_этапа = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Исполнитель третьего этапа]", Storage="_Исполнитель_третьего_этапа", DbType="NVarChar(50)")]
		public string Исполнитель_третьего_этапа
		{
			get
			{
				return this._Исполнитель_третьего_этапа;
			}
			set
			{
				if ((this._Исполнитель_третьего_этапа != value))
				{
					this._Исполнитель_третьего_этапа = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Задание", DbType="NVarChar(100)")]
		public string Задание
		{
			get
			{
				return this._Задание;
			}
			set
			{
				if ((this._Задание != value))
				{
					this._Задание = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Первый этап]", Storage="_Первый_этап", DbType="NVarChar(1)")]
		public string Первый_этап
		{
			get
			{
				return this._Первый_этап;
			}
			set
			{
				if ((this._Первый_этап != value))
				{
					this._Первый_этап = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Второй этап]", Storage="_Второй_этап", DbType="NVarChar(1)")]
		public string Второй_этап
		{
			get
			{
				return this._Второй_этап;
			}
			set
			{
				if ((this._Второй_этап != value))
				{
					this._Второй_этап = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Третий этап]", Storage="_Третий_этап", DbType="NVarChar(1)")]
		public string Третий_этап
		{
			get
			{
				return this._Третий_этап;
			}
			set
			{
				if ((this._Третий_этап != value))
				{
					this._Третий_этап = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SkladView")]
	public partial class SkladView
	{
		
		private string _Заказчик;
		
		private string _Ответственный;
		
		private string _Тип_оборудования;
		
		private string _Серийный_номер;
		
		private string _Модель_оборудования;
		
		private string _СТБ;
		
		public SkladView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Заказчик", DbType="NVarChar(50)")]
		public string Заказчик
		{
			get
			{
				return this._Заказчик;
			}
			set
			{
				if ((this._Заказчик != value))
				{
					this._Заказчик = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ответственный", DbType="NVarChar(50)")]
		public string Ответственный
		{
			get
			{
				return this._Ответственный;
			}
			set
			{
				if ((this._Ответственный != value))
				{
					this._Ответственный = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Тип_оборудования", DbType="NVarChar(50)")]
		public string Тип_оборудования
		{
			get
			{
				return this._Тип_оборудования;
			}
			set
			{
				if ((this._Тип_оборудования != value))
				{
					this._Тип_оборудования = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Серийный_номер", DbType="NVarChar(50)")]
		public string Серийный_номер
		{
			get
			{
				return this._Серийный_номер;
			}
			set
			{
				if ((this._Серийный_номер != value))
				{
					this._Серийный_номер = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Модель_оборудования", DbType="NVarChar(30)")]
		public string Модель_оборудования
		{
			get
			{
				return this._Модель_оборудования;
			}
			set
			{
				if ((this._Модель_оборудования != value))
				{
					this._Модель_оборудования = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СТБ", DbType="NVarChar(30)")]
		public string СТБ
		{
			get
			{
				return this._СТБ;
			}
			set
			{
				if ((this._СТБ != value))
				{
					this._СТБ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SkladBas")]
	public partial class SkladBas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_sklad;
		
		private string _name_item;
		
		private string _name_manufacture;
		
		private string _country;
		
		private string _number;
		
		private string _model_item;
		
		private string _name_man;
		
		private string _lider_man;
		
		private string _STB;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_skladChanging(int value);
    partial void OnId_skladChanged();
    partial void Onname_itemChanging(string value);
    partial void Onname_itemChanged();
    partial void Onname_manufactureChanging(string value);
    partial void Onname_manufactureChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnnumberChanging(string value);
    partial void OnnumberChanged();
    partial void Onmodel_itemChanging(string value);
    partial void Onmodel_itemChanged();
    partial void Onname_manChanging(string value);
    partial void Onname_manChanged();
    partial void Onlider_manChanging(string value);
    partial void Onlider_manChanged();
    partial void OnSTBChanging(string value);
    partial void OnSTBChanged();
    #endregion
		
		public SkladBas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sklad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_sklad
		{
			get
			{
				return this._Id_sklad;
			}
			set
			{
				if ((this._Id_sklad != value))
				{
					this.OnId_skladChanging(value);
					this.SendPropertyChanging();
					this._Id_sklad = value;
					this.SendPropertyChanged("Id_sklad");
					this.OnId_skladChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_item", DbType="NVarChar(50)")]
		public string name_item
		{
			get
			{
				return this._name_item;
			}
			set
			{
				if ((this._name_item != value))
				{
					this.Onname_itemChanging(value);
					this.SendPropertyChanging();
					this._name_item = value;
					this.SendPropertyChanged("name_item");
					this.Onname_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_manufacture", DbType="NVarChar(50)")]
		public string name_manufacture
		{
			get
			{
				return this._name_manufacture;
			}
			set
			{
				if ((this._name_manufacture != value))
				{
					this.Onname_manufactureChanging(value);
					this.SendPropertyChanging();
					this._name_manufacture = value;
					this.SendPropertyChanged("name_manufacture");
					this.Onname_manufactureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(50)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="NVarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_item", DbType="NVarChar(30)")]
		public string model_item
		{
			get
			{
				return this._model_item;
			}
			set
			{
				if ((this._model_item != value))
				{
					this.Onmodel_itemChanging(value);
					this.SendPropertyChanging();
					this._model_item = value;
					this.SendPropertyChanged("model_item");
					this.Onmodel_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_man", DbType="NVarChar(50)")]
		public string name_man
		{
			get
			{
				return this._name_man;
			}
			set
			{
				if ((this._name_man != value))
				{
					this.Onname_manChanging(value);
					this.SendPropertyChanging();
					this._name_man = value;
					this.SendPropertyChanged("name_man");
					this.Onname_manChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lider_man", DbType="NVarChar(50)")]
		public string lider_man
		{
			get
			{
				return this._lider_man;
			}
			set
			{
				if ((this._lider_man != value))
				{
					this.Onlider_manChanging(value);
					this.SendPropertyChanging();
					this._lider_man = value;
					this.SendPropertyChanged("lider_man");
					this.Onlider_manChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STB", DbType="NVarChar(50)")]
		public string STB
		{
			get
			{
				return this._STB;
			}
			set
			{
				if ((this._STB != value))
				{
					this.OnSTBChanging(value);
					this.SendPropertyChanging();
					this._STB = value;
					this.SendPropertyChanged("STB");
					this.OnSTBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Country")]
	public partial class Country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_count;
		
		private string _country1;
		
		private EntitySet<Lessons> _Lessons;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_countChanging(int value);
    partial void Onid_countChanged();
    partial void Oncountry1Changing(string value);
    partial void Oncountry1Changed();
    #endregion
		
		public Country()
		{
			this._Lessons = new EntitySet<Lessons>(new Action<Lessons>(this.attach_Lessons), new Action<Lessons>(this.detach_Lessons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_count", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_count
		{
			get
			{
				return this._id_count;
			}
			set
			{
				if ((this._id_count != value))
				{
					this.Onid_countChanging(value);
					this.SendPropertyChanging();
					this._id_count = value;
					this.SendPropertyChanged("id_count");
					this.Onid_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="country", Storage="_country1", DbType="NVarChar(50)")]
		public string country1
		{
			get
			{
				return this._country1;
			}
			set
			{
				if ((this._country1 != value))
				{
					this.Oncountry1Changing(value);
					this.SendPropertyChanging();
					this._country1 = value;
					this.SendPropertyChanged("country1");
					this.Oncountry1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Country_Lessons", Storage="_Lessons", ThisKey="id_count", OtherKey="id_fk_les1")]
		public EntitySet<Lessons> Lessons
		{
			get
			{
				return this._Lessons;
			}
			set
			{
				this._Lessons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Country = this;
		}
		
		private void detach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Country = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Items : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_item;
		
		private string _name_items;
		
		private EntitySet<Lessons> _Lessons;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    partial void Onname_itemsChanging(string value);
    partial void Onname_itemsChanged();
    #endregion
		
		public Items()
		{
			this._Lessons = new EntitySet<Lessons>(new Action<Lessons>(this.attach_Lessons), new Action<Lessons>(this.detach_Lessons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_items", DbType="NVarChar(50)")]
		public string name_items
		{
			get
			{
				return this._name_items;
			}
			set
			{
				if ((this._name_items != value))
				{
					this.Onname_itemsChanging(value);
					this.SendPropertyChanging();
					this._name_items = value;
					this.SendPropertyChanged("name_items");
					this.Onname_itemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Items_Lessons", Storage="_Lessons", ThisKey="id_item", OtherKey="id_fk_les")]
		public EntitySet<Lessons> Lessons
		{
			get
			{
				return this._Lessons;
			}
			set
			{
				this._Lessons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Items = this;
		}
		
		private void detach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Items = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manufacture")]
	public partial class Manufacture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_man;
		
		private string _manufacture1;
		
		private EntitySet<Lessons> _Lessons;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_manChanging(int value);
    partial void Onid_manChanged();
    partial void Onmanufacture1Changing(string value);
    partial void Onmanufacture1Changed();
    #endregion
		
		public Manufacture()
		{
			this._Lessons = new EntitySet<Lessons>(new Action<Lessons>(this.attach_Lessons), new Action<Lessons>(this.detach_Lessons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_man", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_man
		{
			get
			{
				return this._id_man;
			}
			set
			{
				if ((this._id_man != value))
				{
					this.Onid_manChanging(value);
					this.SendPropertyChanging();
					this._id_man = value;
					this.SendPropertyChanged("id_man");
					this.Onid_manChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="manufacture", Storage="_manufacture1", DbType="NVarChar(50)")]
		public string manufacture1
		{
			get
			{
				return this._manufacture1;
			}
			set
			{
				if ((this._manufacture1 != value))
				{
					this.Onmanufacture1Changing(value);
					this.SendPropertyChanging();
					this._manufacture1 = value;
					this.SendPropertyChanged("manufacture1");
					this.Onmanufacture1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manufacture_Lessons", Storage="_Lessons", ThisKey="id_man", OtherKey="id_fk_les2")]
		public EntitySet<Lessons> Lessons
		{
			get
			{
				return this._Lessons;
			}
			set
			{
				this._Lessons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Manufacture = this;
		}
		
		private void detach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Manufacture = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Model")]
	public partial class Model : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_model;
		
		private string _model1;
		
		private EntitySet<Lessons> _Lessons;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_modelChanging(int value);
    partial void Onid_modelChanged();
    partial void Onmodel1Changing(string value);
    partial void Onmodel1Changed();
    #endregion
		
		public Model()
		{
			this._Lessons = new EntitySet<Lessons>(new Action<Lessons>(this.attach_Lessons), new Action<Lessons>(this.detach_Lessons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_model", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_model
		{
			get
			{
				return this._id_model;
			}
			set
			{
				if ((this._id_model != value))
				{
					this.Onid_modelChanging(value);
					this.SendPropertyChanging();
					this._id_model = value;
					this.SendPropertyChanged("id_model");
					this.Onid_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="model", Storage="_model1", DbType="NVarChar(50)")]
		public string model1
		{
			get
			{
				return this._model1;
			}
			set
			{
				if ((this._model1 != value))
				{
					this.Onmodel1Changing(value);
					this.SendPropertyChanging();
					this._model1 = value;
					this.SendPropertyChanged("model1");
					this.Onmodel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Lessons", Storage="_Lessons", ThisKey="id_model", OtherKey="id_fk_les3")]
		public EntitySet<Lessons> Lessons
		{
			get
			{
				return this._Lessons;
			}
			set
			{
				this._Lessons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STB")]
	public partial class STB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_stb;
		
		private string _stb1;
		
		private EntitySet<Lessons> _Lessons;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_stbChanging(int value);
    partial void Onid_stbChanged();
    partial void Onstb1Changing(string value);
    partial void Onstb1Changed();
    #endregion
		
		public STB()
		{
			this._Lessons = new EntitySet<Lessons>(new Action<Lessons>(this.attach_Lessons), new Action<Lessons>(this.detach_Lessons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_stb", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_stb
		{
			get
			{
				return this._id_stb;
			}
			set
			{
				if ((this._id_stb != value))
				{
					this.Onid_stbChanging(value);
					this.SendPropertyChanging();
					this._id_stb = value;
					this.SendPropertyChanged("id_stb");
					this.Onid_stbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="stb", Storage="_stb1", DbType="NVarChar(50)")]
		public string stb1
		{
			get
			{
				return this._stb1;
			}
			set
			{
				if ((this._stb1 != value))
				{
					this.Onstb1Changing(value);
					this.SendPropertyChanging();
					this._stb1 = value;
					this.SendPropertyChanged("stb1");
					this.Onstb1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STB_Lessons", Storage="_Lessons", ThisKey="id_stb", OtherKey="id_fk_les4")]
		public EntitySet<Lessons> Lessons
		{
			get
			{
				return this._Lessons;
			}
			set
			{
				this._Lessons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.STB = this;
		}
		
		private void detach_Lessons(Lessons entity)
		{
			this.SendPropertyChanging();
			entity.STB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lessons")]
	public partial class Lessons : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_lessons;
		
		private string _FIO_first;
		
		private string _FIO_second;
		
		private string _FIO_there;
		
		private string _Lesson;
		
		private string _End_date;
		
		private string _Date_start;
		
		private string _Laba;
		
		private string _NameFileLaba;
		
		private string _Securit;
		
		private string _NameFileSecurity;
		
		private string _Check_lessons;
		
		private string _NameFilelessons;
		
		private int _id_fk_les;
		
		private int _id_fk_les1;
		
		private int _id_fk_les2;
		
		private int _id_fk_les3;
		
		private int _id_fk_les4;
		
		private EntityRef<Items> _Items;
		
		private EntityRef<Country> _Country;
		
		private EntityRef<Manufacture> _Manufacture;
		
		private EntityRef<Model> _Model;
		
		private EntityRef<STB> _STB;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_lessonsChanging(int value);
    partial void OnId_lessonsChanged();
    partial void OnFIO_firstChanging(string value);
    partial void OnFIO_firstChanged();
    partial void OnFIO_secondChanging(string value);
    partial void OnFIO_secondChanged();
    partial void OnFIO_thereChanging(string value);
    partial void OnFIO_thereChanged();
    partial void OnLessonChanging(string value);
    partial void OnLessonChanged();
    partial void OnEnd_dateChanging(string value);
    partial void OnEnd_dateChanged();
    partial void OnDate_startChanging(string value);
    partial void OnDate_startChanged();
    partial void OnLabaChanging(string value);
    partial void OnLabaChanged();
    partial void OnNameFileLabaChanging(string value);
    partial void OnNameFileLabaChanged();
    partial void OnSecuritChanging(string value);
    partial void OnSecuritChanged();
    partial void OnNameFileSecurityChanging(string value);
    partial void OnNameFileSecurityChanged();
    partial void OnCheck_lessonsChanging(string value);
    partial void OnCheck_lessonsChanged();
    partial void OnNameFilelessonsChanging(string value);
    partial void OnNameFilelessonsChanged();
    partial void Onid_fk_lesChanging(int value);
    partial void Onid_fk_lesChanged();
    partial void Onid_fk_les1Changing(int value);
    partial void Onid_fk_les1Changed();
    partial void Onid_fk_les2Changing(int value);
    partial void Onid_fk_les2Changed();
    partial void Onid_fk_les3Changing(int value);
    partial void Onid_fk_les3Changed();
    partial void Onid_fk_les4Changing(int value);
    partial void Onid_fk_les4Changed();
    #endregion
		
		public Lessons()
		{
			this._Items = default(EntityRef<Items>);
			this._Country = default(EntityRef<Country>);
			this._Manufacture = default(EntityRef<Manufacture>);
			this._Model = default(EntityRef<Model>);
			this._STB = default(EntityRef<STB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_lessons", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_lessons
		{
			get
			{
				return this._Id_lessons;
			}
			set
			{
				if ((this._Id_lessons != value))
				{
					this.OnId_lessonsChanging(value);
					this.SendPropertyChanging();
					this._Id_lessons = value;
					this.SendPropertyChanged("Id_lessons");
					this.OnId_lessonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO_first", DbType="NVarChar(50)")]
		public string FIO_first
		{
			get
			{
				return this._FIO_first;
			}
			set
			{
				if ((this._FIO_first != value))
				{
					this.OnFIO_firstChanging(value);
					this.SendPropertyChanging();
					this._FIO_first = value;
					this.SendPropertyChanged("FIO_first");
					this.OnFIO_firstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO_second", DbType="NVarChar(50)")]
		public string FIO_second
		{
			get
			{
				return this._FIO_second;
			}
			set
			{
				if ((this._FIO_second != value))
				{
					this.OnFIO_secondChanging(value);
					this.SendPropertyChanging();
					this._FIO_second = value;
					this.SendPropertyChanged("FIO_second");
					this.OnFIO_secondChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO_there", DbType="NVarChar(50)")]
		public string FIO_there
		{
			get
			{
				return this._FIO_there;
			}
			set
			{
				if ((this._FIO_there != value))
				{
					this.OnFIO_thereChanging(value);
					this.SendPropertyChanging();
					this._FIO_there = value;
					this.SendPropertyChanged("FIO_there");
					this.OnFIO_thereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lesson", DbType="NVarChar(100)")]
		public string Lesson
		{
			get
			{
				return this._Lesson;
			}
			set
			{
				if ((this._Lesson != value))
				{
					this.OnLessonChanging(value);
					this.SendPropertyChanging();
					this._Lesson = value;
					this.SendPropertyChanged("Lesson");
					this.OnLessonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_date", DbType="NVarChar(20)")]
		public string End_date
		{
			get
			{
				return this._End_date;
			}
			set
			{
				if ((this._End_date != value))
				{
					this.OnEnd_dateChanging(value);
					this.SendPropertyChanging();
					this._End_date = value;
					this.SendPropertyChanged("End_date");
					this.OnEnd_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_start", DbType="NVarChar(20)")]
		public string Date_start
		{
			get
			{
				return this._Date_start;
			}
			set
			{
				if ((this._Date_start != value))
				{
					this.OnDate_startChanging(value);
					this.SendPropertyChanging();
					this._Date_start = value;
					this.SendPropertyChanged("Date_start");
					this.OnDate_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Laba", DbType="NVarChar(1)")]
		public string Laba
		{
			get
			{
				return this._Laba;
			}
			set
			{
				if ((this._Laba != value))
				{
					this.OnLabaChanging(value);
					this.SendPropertyChanging();
					this._Laba = value;
					this.SendPropertyChanged("Laba");
					this.OnLabaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameFileLaba", DbType="NVarChar(MAX)")]
		public string NameFileLaba
		{
			get
			{
				return this._NameFileLaba;
			}
			set
			{
				if ((this._NameFileLaba != value))
				{
					this.OnNameFileLabaChanging(value);
					this.SendPropertyChanging();
					this._NameFileLaba = value;
					this.SendPropertyChanged("NameFileLaba");
					this.OnNameFileLabaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Securit", DbType="NVarChar(1)")]
		public string Securit
		{
			get
			{
				return this._Securit;
			}
			set
			{
				if ((this._Securit != value))
				{
					this.OnSecuritChanging(value);
					this.SendPropertyChanging();
					this._Securit = value;
					this.SendPropertyChanged("Securit");
					this.OnSecuritChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameFileSecurity", DbType="NVarChar(MAX)")]
		public string NameFileSecurity
		{
			get
			{
				return this._NameFileSecurity;
			}
			set
			{
				if ((this._NameFileSecurity != value))
				{
					this.OnNameFileSecurityChanging(value);
					this.SendPropertyChanging();
					this._NameFileSecurity = value;
					this.SendPropertyChanged("NameFileSecurity");
					this.OnNameFileSecurityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_lessons", DbType="NVarChar(1)")]
		public string Check_lessons
		{
			get
			{
				return this._Check_lessons;
			}
			set
			{
				if ((this._Check_lessons != value))
				{
					this.OnCheck_lessonsChanging(value);
					this.SendPropertyChanging();
					this._Check_lessons = value;
					this.SendPropertyChanged("Check_lessons");
					this.OnCheck_lessonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameFilelessons", DbType="NVarChar(MAX)")]
		public string NameFilelessons
		{
			get
			{
				return this._NameFilelessons;
			}
			set
			{
				if ((this._NameFilelessons != value))
				{
					this.OnNameFilelessonsChanging(value);
					this.SendPropertyChanging();
					this._NameFilelessons = value;
					this.SendPropertyChanged("NameFilelessons");
					this.OnNameFilelessonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fk_les", DbType="Int NOT NULL")]
		public int id_fk_les
		{
			get
			{
				return this._id_fk_les;
			}
			set
			{
				if ((this._id_fk_les != value))
				{
					if (this._Items.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fk_lesChanging(value);
					this.SendPropertyChanging();
					this._id_fk_les = value;
					this.SendPropertyChanged("id_fk_les");
					this.Onid_fk_lesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fk_les1", DbType="Int NOT NULL")]
		public int id_fk_les1
		{
			get
			{
				return this._id_fk_les1;
			}
			set
			{
				if ((this._id_fk_les1 != value))
				{
					if (this._Country.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fk_les1Changing(value);
					this.SendPropertyChanging();
					this._id_fk_les1 = value;
					this.SendPropertyChanged("id_fk_les1");
					this.Onid_fk_les1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fk_les2", DbType="Int NOT NULL")]
		public int id_fk_les2
		{
			get
			{
				return this._id_fk_les2;
			}
			set
			{
				if ((this._id_fk_les2 != value))
				{
					if (this._Manufacture.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fk_les2Changing(value);
					this.SendPropertyChanging();
					this._id_fk_les2 = value;
					this.SendPropertyChanged("id_fk_les2");
					this.Onid_fk_les2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fk_les3", DbType="Int NOT NULL")]
		public int id_fk_les3
		{
			get
			{
				return this._id_fk_les3;
			}
			set
			{
				if ((this._id_fk_les3 != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fk_les3Changing(value);
					this.SendPropertyChanging();
					this._id_fk_les3 = value;
					this.SendPropertyChanged("id_fk_les3");
					this.Onid_fk_les3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fk_les4", DbType="Int NOT NULL")]
		public int id_fk_les4
		{
			get
			{
				return this._id_fk_les4;
			}
			set
			{
				if ((this._id_fk_les4 != value))
				{
					if (this._STB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fk_les4Changing(value);
					this.SendPropertyChanging();
					this._id_fk_les4 = value;
					this.SendPropertyChanged("id_fk_les4");
					this.Onid_fk_les4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Items_Lessons", Storage="_Items", ThisKey="id_fk_les", OtherKey="id_item", IsForeignKey=true)]
		public Items Items
		{
			get
			{
				return this._Items.Entity;
			}
			set
			{
				Items previousValue = this._Items.Entity;
				if (((previousValue != value) 
							|| (this._Items.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Items.Entity = null;
						previousValue.Lessons.Remove(this);
					}
					this._Items.Entity = value;
					if ((value != null))
					{
						value.Lessons.Add(this);
						this._id_fk_les = value.id_item;
					}
					else
					{
						this._id_fk_les = default(int);
					}
					this.SendPropertyChanged("Items");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Country_Lessons", Storage="_Country", ThisKey="id_fk_les1", OtherKey="id_count", IsForeignKey=true)]
		public Country Country
		{
			get
			{
				return this._Country.Entity;
			}
			set
			{
				Country previousValue = this._Country.Entity;
				if (((previousValue != value) 
							|| (this._Country.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Country.Entity = null;
						previousValue.Lessons.Remove(this);
					}
					this._Country.Entity = value;
					if ((value != null))
					{
						value.Lessons.Add(this);
						this._id_fk_les1 = value.id_count;
					}
					else
					{
						this._id_fk_les1 = default(int);
					}
					this.SendPropertyChanged("Country");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manufacture_Lessons", Storage="_Manufacture", ThisKey="id_fk_les2", OtherKey="id_man", IsForeignKey=true)]
		public Manufacture Manufacture
		{
			get
			{
				return this._Manufacture.Entity;
			}
			set
			{
				Manufacture previousValue = this._Manufacture.Entity;
				if (((previousValue != value) 
							|| (this._Manufacture.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Manufacture.Entity = null;
						previousValue.Lessons.Remove(this);
					}
					this._Manufacture.Entity = value;
					if ((value != null))
					{
						value.Lessons.Add(this);
						this._id_fk_les2 = value.id_man;
					}
					else
					{
						this._id_fk_les2 = default(int);
					}
					this.SendPropertyChanged("Manufacture");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Lessons", Storage="_Model", ThisKey="id_fk_les3", OtherKey="id_model", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.Lessons.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.Lessons.Add(this);
						this._id_fk_les3 = value.id_model;
					}
					else
					{
						this._id_fk_les3 = default(int);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STB_Lessons", Storage="_STB", ThisKey="id_fk_les4", OtherKey="id_stb", IsForeignKey=true)]
		public STB STB
		{
			get
			{
				return this._STB.Entity;
			}
			set
			{
				STB previousValue = this._STB.Entity;
				if (((previousValue != value) 
							|| (this._STB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STB.Entity = null;
						previousValue.Lessons.Remove(this);
					}
					this._STB.Entity = value;
					if ((value != null))
					{
						value.Lessons.Add(this);
						this._id_fk_les4 = value.id_stb;
					}
					else
					{
						this._id_fk_les4 = default(int);
					}
					this.SendPropertyChanged("STB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
